# Default values
DEFAULT_DB_URL = "sqlite:///tracker.db"
DEFAULT_TRK_HOST = "172.20.0.2"
DEFAULT_TRK_PORT = "5555"
DEFAULT_DEBUG = False

DEFAULT_DL_PATH = "./downloads"
DEFAULT_TN_PATH = "./torrents"
DEFAULT_TK_URL = "172.20.0.2:5555"
DEFAULT_LT_PORT = 6881
DEFAULT_MAX_DL_RATE = 0
DEFAULT_MAX_UL_RATE = 0
DEFAULT_MAX_CON = 200
