DEFAULT_DB_URL = "sqlite+aiosqlite:///tracker.db"
DEFAULT_DB_ECHO = False
DEFAULT_DB_POOL_SIZE = 10
DEFAULT_DB_MAX_OVERFLOW = 20
DEFAULT_DB_POOL_RECYCLE = 3600
DEFAULT_TRK_HOST = "0.0.0.0"
DEFAULT_TRK_PORT = 5555
DEFAULT_GEN_PORT = 70
